{% set data = load_setup_py_data() %}

package:
    name: mflow
    version: {{ data["version"] }}

about:
   home: {{ data["url"] }}
   summary: {{ data["description"] }}

source:
    path: ..

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - m_dump = mflow.cli.dump:main
    - m_replay = mflow.cli.replay:main
    - m_stats = mflow.cli.stats:main
    - m_split = mflow.cli.split:main
    - m_generate = mflow.cli.generate:main

requirements:
    build:
        - python >=3.1
        - setuptools
        - pip
    run:
        - python >=3.1
        - pyzmq

